# Generated by Django 4.1.4 on 2023-01-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Customer'), (1, 'Seller')], null=True),
        ),
    ]
