# Generated by Django 4.1.4 on 2023-01-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='products'),
        ),
    ]
