# Generated by Django 4.1.5 on 2023-01-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='product',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='user',
        ),
    ]
